# Generated by Django 2.0.2 on 2018-10-18 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DCategory',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=20)),
                ('book_counts', models.IntegerField()),
                ('category_pid', models.IntegerField()),
            ],
            options={
                'db_table': 'd_category',
            },
        ),
        migrations.CreateModel(
            name='DOrderiterm',
            fields=[
                ('shop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('shop_num', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'd_orderiterm',
            },
        ),
        migrations.CreateModel(
            name='TAddress',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('detail_address', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('telphone', models.CharField(max_length=20)),
                ('addr_mobile', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 't_address',
            },
        ),
        migrations.CreateModel(
            name='TBook',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=128)),
                ('book_author', models.CharField(max_length=64)),
                ('book_publish', models.CharField(max_length=128)),
                ('publish_time', models.DateTimeField()),
                ('revision', models.IntegerField()),
                ('book_isbn', models.CharField(max_length=64)),
                ('word_count', models.CharField(max_length=64)),
                ('page_count', models.IntegerField()),
                ('open_type', models.CharField(max_length=20)),
                ('book_paper', models.CharField(max_length=64)),
                ('book_wrapper', models.CharField(max_length=64)),
                ('book_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('book_dprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('editor_recommendation', models.CharField(max_length=200)),
                ('content_introduction', models.CharField(max_length=200)),
                ('author_introduction', models.CharField(max_length=200)),
                ('menu', models.CharField(max_length=200)),
                ('media_review', models.CharField(max_length=200)),
                ('digest_image_path', models.CharField(max_length=200)),
                ('product_image_path', models.CharField(max_length=200)),
                ('series_name', models.CharField(max_length=200)),
                ('printing_time', models.DateTimeField()),
                ('impression', models.CharField(max_length=64)),
                ('stock', models.IntegerField()),
                ('shelves_date', models.DateTimeField()),
                ('customer_socre', models.DecimalField(decimal_places=2, max_digits=3)),
                ('book_status', models.IntegerField()),
                ('sales', models.IntegerField()),
                ('book_category', models.ForeignKey(db_column='book_category', on_delete=django.db.models.deletion.DO_NOTHING, to='main_page_app.DCategory')),
            ],
            options={
                'db_table': 't_book',
            },
        ),
        migrations.CreateModel(
            name='TOrder',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('num', models.IntegerField()),
                ('create_date', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('status', models.IntegerField()),
                ('order_addrid', models.ForeignKey(db_column='order_addrid', on_delete=django.db.models.deletion.DO_NOTHING, to='main_page_app.TAddress')),
            ],
            options={
                'db_table': 't_order',
            },
        ),
        migrations.CreateModel(
            name='TUser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_email', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=30)),
                ('user_status', models.IntegerField()),
            ],
            options={
                'db_table': 't_user',
            },
        ),
        migrations.AddField(
            model_name='torder',
            name='order_uid',
            field=models.ForeignKey(db_column='order_uid', on_delete=django.db.models.deletion.DO_NOTHING, to='main_page_app.TUser'),
        ),
        migrations.AddField(
            model_name='taddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_page_app.TUser'),
        ),
        migrations.AddField(
            model_name='dorderiterm',
            name='shop_bookid',
            field=models.ForeignKey(db_column='shop_bookid', on_delete=django.db.models.deletion.DO_NOTHING, to='main_page_app.TBook'),
        ),
        migrations.AddField(
            model_name='dorderiterm',
            name='shop_ordid',
            field=models.ForeignKey(db_column='shop_ordid', on_delete=django.db.models.deletion.DO_NOTHING, to='main_page_app.TOrder'),
        ),
    ]
